// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvjfpkyaqlmuabkohiai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2amZwa3lhcWxtdWFia29oaWFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5Mjg3NDcsImV4cCI6MjA2OTUwNDc0N30.7ynqfIa7TxhXXbqnSQn-zIyKBfXqhDFKaOUD8c6Fwz8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});